feat: 추천작가 구현 완료
SOPT-28/brunch-front pull request #4
Opened 2021-05-19 10:05 UTC by gytks4

추천작가 구현 완료

2021-05-19 12:24 UTC, juno7803 requested changes
전체적으로 잘 했음!
리뷰 달아놓은 내용 수정해서 커밋 날리면, pr 다시 안날려도 자동으로 반영되니까 
커밋만 남겨줘!

추가) pr 양식은 정해진건 없지만,
"추천작가 구현 완료" 라고 적혀진 부분에
### Summary
- 웹 폰트 "Noto-serif" 적용
- 컴포넌트 분리
- eslint 수정

막 이런식으로 리뷰어가 리뷰할 때 어떤 내용들인지 알기 쉽도록 구현한 내용을 첨부해주면 좋아 :)

2021-05-19 12:24 UTC, juno7803 commented on src/components/main/writers.js
> +          <img src={WriterSixth} className="writers__card"></img>
img 태그는 `<img />`로 닫아주는게 더 좋을 것 같아!

2021-05-19 12:24 UTC, juno7803 commented on src/components/main/writers.js
> +      /* 글씨 어떻게 조정하지? */
https://velog.io/@mokyoungg/Styled-Components-import-font
해당 링크 참고하면 쓸 수 있어! 근데 요건 내가 세팅해주는게 맞을 것 같아서 내가 적용하구 말해줄게!

2021-05-19 12:24 UTC, juno7803 commented on src/components/main/writers.js
> +        /* color: #289bd1; */
주석 지워주면 좋을 것 같아 :)

그리구, 컴포넌트는 이름 지을때 **Pascal Case**로 지어야 해!
그니까 여기선 `Writer.js` 로 바꿔야 함!

2021-05-19 12:24 UTC, juno7803 commented on src/pages/MainPage.js
> +import Writers from '../components/main/writers';
`Wirters.js` 컴포넌트도 `index.js`안에 선언해줘서
```jsx
import { Writers } from '../components';
```
처럼 쓸 수 있게 바꿔주면 좋을 것 같아!

2021-05-19 12:24 UTC, juno7803 commented on src/components/main/recommendedArticles.js
> +export default RecommendedArticles;
여기도 컴포넌트 이름은 Pascal Case로 부탁해!

2021-05-20 03:37 UTC, juno7803 commented on src/pages/MainPage.js
> +import { Writers } from '../components/index';
`index.js`는 기본적으루 vscode에서 제일 기본 파일로 인식을 해!
무슨말이냐면, 
```jsx
import { Writers } from '../components';
```
라고만 하고 `index` 를 생략해도 된다는 뜻!

2021-05-20 03:46 UTC, juno7803 commented
LGTM

2021-05-20 03:46 UTC, merged

2021-05-20 05:13 UTC, gytks4 commented on src/pages/MainPage.js
> +import { Writers } from '../components/index';
와 몰랐다... 고마워!